receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"

processors:

exporters:
# prometheus:
#    endpoint: "0.0.0.0:8889"
  rest:
    endpoint: "0.0.0.0:8890"  # あなたのRESTエンドポイントに合わせて変更してください

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: []
      exporters: [rest]
      #exporters: [prometheus, rest]