services:
  otel-collector:
    build:
      context: ./../..
      dockerfile: Dockerfile
    command: ["/usr/local/bin/custom-otel-collector", "--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./../../otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"   # OTLP gRPC receiver
      - "8889:8889"   # Prometheus exporter
      - "8890:8890"

  prometheus:
    depends_on:
      - otel-collector
    image: prom/prometheus:latest
    volumes:
      - ./../prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  metrics-sender:
    build:
      context: ./
      dockerfile: Dockerfile
    command: ["/usr/local/bin/metrics-sender"]